# Generated by Django 3.0.3 on 2020-08-11 16:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.CharField(default='', max_length=100)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photodes', models.TextField(blank=True, default='', max_length=1000)),
                ('photo1', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo2', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo3', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_name', models.CharField(max_length=200)),
                ('comment_text', ckeditor.fields.RichTextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newscomments', to='blog.NewsPost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photodes', models.TextField(blank=True, default='', max_length=1000)),
                ('photo1', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo2', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo3', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_name', models.CharField(max_length=200)),
                ('comment_text', ckeditor.fields.RichTextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogcomments', to='blog.BlogPost')),
            ],
        ),
    ]
