# Generated by Django 3.0.3 on 2020-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200811_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='commentor_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
