# Generated by Django 3.0.3 on 2020-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200811_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='commentor_name',
            field=models.CharField(default='Visitor', max_length=200),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='commentor_name',
            field=models.CharField(default='Visitor', max_length=200),
        ),
    ]
