# Generated by Django 3.0.3 on 2020-08-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200811_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='photodes',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='photodes',
        ),
    ]
